// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vanlofhgxdmuhqeopjwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbmxvZmhneGRtdWhxZW9wandvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODI2NjYsImV4cCI6MjA2NjI1ODY2Nn0.S2ibc3rRPsFxmEQoeOg5h4KR8D6zVPnXwMZDGwwz2q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);